# Eye Friendly Colors
# Created by https://github.com/decaycs

[colors.bright]
black = "#384148"
blue = "#8cc1ff"
cyan = "#90daff"
green = "#94f7c5"
magenta = "#e2a6ff"
red = "#fc7b81"
white = "#fafdff"
yellow = "#ffeba6"

[colors.cursor]
cursor = "#f5f5f5"
text = "CellForeground"

[colors.normal]
black = "#1c252c"
blue = "#70a5eb"
cyan = "#74bee9"
green = "#78dba9"
magenta = "#c68aee"
red = "#e05f65"
white = "#dee1e6"
yellow = "#f1cf8a"

[colors.primary]
background = "#101419"
foreground = "#b6beca"
