# Eye Friendly Colors
# Created by https://github.com/decaycs

[colors.bright]
black = "#151720"
blue = "#86aaec"
cyan = "#93cee9"
green = "#90ceaa"
magenta = "#c296eb"
red = "#dd6777"
white = "#cbced3"
yellow = "#ecd3a0"

[colors.cursor]
cursor = "#a5b6cf"
text = "CellForeground"

[colors.normal]
black = "#1c1e27"
blue = "#8baff1"
cyan = "#98d3ee"
green = "#95d3af"
magenta = "#c79bf0"
red = "#e26c7c"
white = "#d0d3d8"
yellow = "#f1d8a5"

[colors.primary]
background = "#0d0f18"
foreground = "#a5b6cf"
